language: php
addons:
    chrome: stable

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2

install:
    - composer install --no-interaction --prefer-dist

script:
    - php vendor/bin/phpcs --standard=PSR12 --ignore=./src/Resources ./src ./tests
    - php vendor/bin/phpstan analyse ./src ./tests --level 7
    - php vendor/bin/phpunit
