language: php
addons:
    chrome: stable

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.3
    - 7.4
    - 8.0

install:
    - composer install --no-interaction --prefer-dist

script:
    - php vendor/bin/phpunit

jobs:
    include:
        -   stage: Code Static Analyze (phpstan)
            php: 8.0
            script:
                - php vendor/bin/phpstan

        -   stage: Code Standard Checker
            php: 8.0
            script:
                - php vendor/bin/phpcs --standard=PSR12 --ignore=./src/Resources ./src ./tests

        -   stage: Code Coverage
            php: 8.0
            script:
                - php vendor/bin/phpunit --coverage-clover ./coverage.xml
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                - php php-coveralls.phar --verbose
