language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1

install:
    - composer install --no-interaction --prefer-dist

script:
    - php vendor/bin/phpstan analyse ./src --level 7
    - php vendor/bin/phpcs --standard=PSR12 --ignore=./src/Resources ./src
