datagrid_ajax:
  path: '/datagrid/ajax/{name}'
  controller: FreezyBee\DataGridBundle\Controller\DataGridController::ajax
  requirements:
    name: '.*'

datagrid_export:
  path: '/datagrid/export/{name}'
  controller: FreezyBee\DataGridBundle\Controller\DataGridController::export
  requirements:
    name: '.*'
